version: '3.1'

services:

  civicrm:
    image: civicrm
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USERNAME=drupal
      - DRUPAL_DB_PASSWORD=password
      - CIVICRM_DB_NAME=civicrm
      - CIVICRM_DB_USERNAME=civicrm
      - CIVICRM_DB_PASSWORD=password
      - SITE_EMAIL=email@example.com
      - TRUSTED_HOST=172.17.0.1:8080
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - ADMIN_EMAIL=admin@example.com
    ports:
      - 8080:80
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
      mode: global

  mariadb:
    image: samirkherraz/mariadb
    environment:
      - ROOT_PASSWORD=password
      - DB_0_NAME=drupal
      - DB_0_PASS=password
      - DB_1_NAME=civicrm
      - DB_1_PASS=password
    ports:
      - 3306:3306
      - 8081:80
    volumes:
      - mariadb-data:/var/lib/mysql/
      - mariadb-config:/etc/mysql/
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
      mode: global

volumes:
    mariadb-data:
    mariadb-config: